### ISSUE TITLE
pushd and popd not implemented

### ISSUE THREAD

**Issue by djerius** [martinec/bash-per-directory-history#1]
Hi,

The README mentions `pushd` and `popd`, but they don't seem to be handled properly.  Only `cd` results in a change to `HISTFILE`.

Am I missing something obvious?

Thanks,
Diab

**Comment by martinec** [comment]
Hi @djerius,

Actually, the native `pushd` and `popd` commands are unmodified. However, there is a new alias `cd` that uses `pushd` and `popd` behind, take a look [here](https://github.com/martinec/bash-per-directory-history/blob/master/per-directory-history.sh#L323) and [here](https://github.com/martinec/bash-per-directory-history/blob/master/per-directory-history.sh#L161).

Thanks for your comment. I just modified the README to make this clearer.
